//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInfo
    {
        public int AddressId { get; set; }
        public string AddressName { get; set; }
        public string AddressNearbyPlace { get; set; }
    }
}
