//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitorId { get; set; }
        public string VisitorName { get; set; }
        public int ContactNo { get; set; }
        public string EMail { get; set; }
        public string Address { get; set; }
    }
}
